FROM node:22

WORKDIR /opt/application
COPY api api

WORKDIR /opt/application/api
RUN npm ci -f
RUN npm run build

CMD npm run build:post \
  && rm -rf ../api-build/node_modules \
  && cp -r node_modules ../api-build \
  && npm start

