FROM node:25

WORKDIR /opt/application
COPY \
  api/package.json \
  api/package-lock.json \
  api/

WORKDIR /opt/application/api
RUN npm ci -f

WORKDIR /opt/application
COPY api api

WORKDIR /opt/application/api
RUN npm run build

CMD npm start

