FROM node:25

WORKDIR /opt/application
COPY \
  web/package.json \
  web/package-lock.json \
  web/

WORKDIR /opt/application/web
RUN npm ci -f

WORKDIR /opt/application
COPY web web
COPY api/src api/src

WORKDIR /opt/application/web
COPY api/.aeria/runtime.js node_modules/aeria-sdk/dist/runtime.js
RUN npm run build

CMD \
  rm -rf /var/www/html/* \
  && mv dist/* /var/www/html

