/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AeriaIcon: typeof import('@aeria-ui/ui')['AeriaIcon']
    AeriaMain: typeof import('@aeria-ui/ui')['AeriaMain']
    NoResults: typeof import('./../src/components/no-results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
