name: Continuos Integration

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: npm
      - name: Install dependencies
        run: npm ci -f
      - name: Build packages
        run: |
          npm --workspace=api run build
          npm --workspace=api run build:icons
          npm --workspace=web run build:ci

