name: Pull Request

on:
  - pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: npm
      - name: Install dependencies
        run: npm ci -f
      - name: Build packages
        run: |
          npm --workspace=api run build
          npm --workspace=api run build:icons
          npm --workspace=web run build:ci

  dependabot:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'aeria-org/quickstart'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve a PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

